config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :work_teams, only: [:index]
  resources :contact_us, only: [:index]
  resources :abouts, only: [:index]
  resources :employees, only: [:index, :show, :new, :create]
  resources :home do
    get 'detail_service', on: :collection
  end
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :jobs
  belongs_to :country
end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :image

  has_many :jobs
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :city
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:admin) if self.roles.blank?
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def detail_service
    
  end
end

app/controllers/work_teams_controller.rb
class WorkTeamsController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/work_teams_helper.rb
module WorkTeamsHelper
end

app/views/abouts/index.html.erb
<section class="about_section layout_padding" data-aos="fade-up">
  <div class="container  ">
    <div class="row">
      <div class="col-md-6 ">
        <div class="img-box">
          <img src="images/about-img.jpg" alt="">
        </div>
      </div>
      <div class="col-md-6">
        <div class="detail-box">
          <div class="heading_container">
            <h2>
              Te ayudamos en la gestión y desarrollo del potencial humano
            </h2>
          </div>
          <p>
            Somos una empresa de servicios en Psicología Organizacional, Educativa y Clínica, orientada a proponer soluciones efectivas y a mejorar la calidad de vida de las personas y/o de las organizaciones de acuerdo con el ámbito en el cual estemos acompañando. Generamos la construcción de modelos adaptados a las necesidades particulares de nuestros clientes, ofreciendo resultados competentes que les permitan alcanzar resultados sostenibles en el largo plazo. 
          </p>
          <p>
            Teniendo presente que cada organización y persona es un mundo único, nuestra propuesta de valor está encaminada a enfocarnos  en los procesos y necesidades particulares de cada uno  para de esta manera ofrecer un acompañamiento con  calidad, en  tiempos de respuesta oportunos y  a costos razonables.
          </p>

        </div>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-6 ">
        <div class="detail-box">
          <div class="heading_container">
            <h2>
              VISION</span>
            </h2>
          </div>
          <p>
           Ser reconocidos a nivel global como una firma de consultoría comprometida en apoyar procesos que potencialicen el talento de las personas en el ámbito empresarial, personal y educativo. En el año 2029 AdsumGT será reconocida como líder en Colombia y tendrá desarrollos a nivel internacional. 
          </p>
        
        </div>
      </div>
      <div class="col-md-6">
        <div class="img-box">
          <img src="images/about-img.jpg" alt="">
        </div>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-6">
        <div class="img-box">
          <img src="images/about-img.jpg" alt="">
        </div>
      </div>
      
      <div class="col-md-6 ">
        <div class="detail-box">
          <div class="heading_container">
            <h2>
              MISIÓN</span>
            </h2>
          </div>
          <p>
           En AdsumGT trabajamos por el desarrollo de las organizaciones y de las personas, siendo motivadores de cambio de actitudes y comportamientos direccionados a la mejora continua. Somos un aliado estratégico de nuestros clientes, generando relaciones de sinergia a través de la construcción de modelos adaptados a las necesidades particulares de cada organización y cumpliendo con altos estándares de calidad. 	 	 
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/contact_us/index.html.erb
<section class="contact_section layout_padding" data-aos="fade-up">
    <div class="container">
      <div class="heading_container">
        <h2>
          Get In Touch
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container contact-form">
            <form action="">
              <div class="form-row">
                <div class="col-lg-6">
                  <div>
                    <input type="text" placeholder="Your Name" />
                  </div>
                </div>
                <div class="col-lg-6">
                  <div>
                    <input type="text" placeholder="Phone Number" />
                  </div>
                </div>
              </div>
              <div>
                <input type="email" placeholder="Email" />
              </div>
              <div>
                <input type="text" class="message-box" placeholder="Message" />
              </div>
              <div class="btn_box">
                <button>
                  SEND
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/index.html.erb
<section class="doctor_section layout_padding" data-aos="fade-up">
  <div class="container">
    <div class="heading_container heading_center">
      <h2>Principales empleos</h2>
    </div>
    <div class="row">
      <div class="col-sm-6 col-lg-4 mx-auto">
        <div class="box">
          <div class="img-container">
            <%= image_tag("Epam.png", alt: "Texto alternativo", class: "img-responsive") %>
          </div>
          <div class="detail-box">
            <h5>Ingeniero de Sistemas</h5>
            <h6>EPAM</h6>
          </div>
          <div class="social_box">
            <a href="#" class="btn btn-sm btn-primary btn-block secondary-button">Ver detalles</a>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-lg-4 mx-auto">
        <div class="box">
          <div class="img-box">
            <img src="images/d2.jpg" alt="">
          </div>
          <div class="detail-box">
            <h5>Administrador Empresas</h5>
            <h6>POLITI</h6>
          </div>
          <div class="social_box">
            <a href="#" class="btn btn-sm btn-primary btn-block secondary-button">Ver detalles</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-lg-4 mx-auto">
        <div class="box">
          <div class="img-box">
            <img src="images/d3.jpg" alt="">
          </div>
          <div class="detail-box">
            <h5>Comunicadora social</h5>
            <h6>Caracol</h6>
          </div>
          <div class="social_box">
            <a href="#" class="btn btn-sm btn-primary btn-block secondary-button">Ver detalles</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="department_section layout_padding" data-aos="fade-up">
  <div class="department_container">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>Mira los demás empleos activos</h2>
      </div>
      <div class="row">
        <div class="col-md-12 mt-5">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Nombre del empleo</th>
                  <th>Empresa</th>
                  <th>Modalidad</th>
                  <th>Ciudad</th>
                  <th>Salario</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Ingeniero de sistemas</td>
                  <td>EPAM</td>
                  <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sapien ut magna ultricies ultricies.</td>
                </tr>
                <tr>
                  <td>Administrador de empresas</td>
                  <td>POLITI</td>
                  <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec sapien ut magna ultricies ultricies.</td>
                </tr>
                <!-- Agrega más filas según sea necesario -->
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
    // Inicializar la librería AOS
    AOS.init({
      duration: 800, // Duración de la animación en milisegundos
      once: true // La animación solo se activará una vez
    });
  </script>

app/views/employees/new.html.erb
<h1>Employees#new</h1>
<p>Find me in app/views/employees/new.html.erb</p>

app/views/employees/show.html.erb
<h1>Employees#show</h1>
<p>Find me in app/views/employees/show.html.erb</p>

app/views/home/_about_us.html.erb
<div class="container  ">
  <div class="row">
    <div class="col-md-6 ">
      <div class="img-box">
        <%= image_tag("AboutUs.png", alt: "Texto alternativo") %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="detail-box">
        <div class="heading_container">
          <h2>
            Sobre <span>nosotros</span>
          </h2>
        </div>
        <p>
          Somos una empresa de servicios en Psicología Organizacional, Educativa y Clínica, orientada a proponer soluciones efectivas y a mejorar la calidad de vida de las personas y/o de las organizaciones de acuerdo con el ámbito en el cual estemos acompañando. Generamos la construcción de modelos adaptados a las necesidades particulares de nuestros clientes, ofreciendo resultados competentes que les permitan alcanzar resultados sostenibles en el largo plazo. 
        </p>
       <%= link_to "Mira mas", abouts_path %>
      </div>
    </div>
  </div>
</div>

app/views/home/_couching.html.erb
<div class="container">
  <div class="heading_container heading_center">
    <h2>
      Couchig
    </h2>
    <p class="col-md-10 mx-auto px-0">
      resumen
    </p>
  </div>
  <div class="row">
    <div class="col-sm-6 col-lg-4 mx-auto">
      <div class="box">
        <div class="img-box">
          <img src="images/d1.jpg" alt="">
        </div>
        <div class="detail-box">
          <div class="social_box">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
          </div>
          <h5>
            Elina Josh
          </h5>
          <h6 class="">
            Doctor
          </h6>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-lg-4 mx-auto">
      <div class="box">
        <div class="img-box">
          <img src="images/d2.jpg" alt="">
        </div>
        <div class="detail-box">
          <div class="social_box">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
          </div>
          <h5>
            Adam View
          </h5>
          <h6 class="">
            Doctor
          </h6>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-lg-4 mx-auto">
      <div class="box">
        <div class="img-box">
          <img src="images/d3.jpg" alt="">
        </div>
        <div class="detail-box">
          <div class="social_box">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
          </div>
          <h5>
            Mia Mike
          </h5>
          <h6 class="">
            Doctor
          </h6>
        </div>
      </div>
    </div>
  </div>
  <div class="btn-box">
    <%= link_to "Mira mas", coachings_path %>
  </div>
</div>

app/views/home/_employes.html.erb
<div class="department_container">
  <div class="container">
    <div class="heading_container heading_center">
      <h2>Mira Nuestros servicios</h2>
      <p>Pasa el mouse sobre las tarjetas para descubrir más. Haz clic en una opción para conocer todos los detalles.</p>
    </div>
    <div class="row">
      <div class="col-md-3">
        <div class="box card" data-url="/url-coaching">
          <div class="img-box">
            <%= image_tag("Coaching.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Atracción y caloración de talentos</h5>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box card" data-url="/url-valoracion">
          <div class="img-box">
            <%= image_tag("Seleccion.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Valoración de potencial</h5>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box card" data-url="/url-capacitacion">
          <div class="img-box">
            <%= image_tag("Training.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Capacitación y desarrollo</h5>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box card" data-url="/url-estudios">
          <div class="img-box">
            <%= image_tag("Organization.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Estudios de Satisfacción y Clima Laboral</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="row covered-row justify-content-center" style="display: none;">
      <!-- Contenido de la fila cubierta -->
      <div class="col-md-3">
        <div class="box card" data-url="/url-coaching">
          <div class="img-box">
            <%= image_tag("Coaching.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Coaching </h5>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box card" data-url="/url-programas-salud">
          <div class="img-box">
            <%= image_tag("Seleccion.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Programas de Salud y Seguridad en el trabajo. </h5>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box card" data-url="/url-programas-salud">
          <div class="img-box">
            <%= image_tag("Seleccion.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Psicología Clínica. </h5>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box card" data-url="/url-programas-salud">
          <div class="img-box">
            <%= image_tag("Seleccion.png", alt: "") %>
          </div>
          <div class="detail-box">
            <h5>Psicología Educativa.</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="btn-box">
      <button class="btn btn-primary" id="ver-mas">Ver más</button>
    </div>
  </div>
</div>


<style>
  .covered-row {
    display: none;
    transition: display 0.5s ease; /* Transición suave con duración de 0.5 segundos */
  }
  .box {
    transition: transform 0.3s ease;
  }

  .box:hover {
    transform: scale(1.05); /* Amplía el card al pasar el mouse */
  }

  .covered-row {
    display: none;
    transition: display 0.5s ease; /* Transición suave con duración de 0.5 segundos */
  }
</style>

<script>
  document.getElementById('ver-mas').addEventListener('click', function() {
    var coveredRow = document.querySelector('.covered-row');
    if (coveredRow.style.display === 'none') {
      coveredRow.style.display = 'flex';
      this.textContent = 'Ver menos'; 
    } else {
      coveredRow.style.display = 'none'; 
      this.textContent = 'Ver más'; 
    }
  });

  document.querySelectorAll('.card').forEach(function(card) {
    card.addEventListener('click', function() {
      window.location.href = card.getAttribute('data-url'); // Redirige a la URL especificada en el atributo data-url
    });
  });
</script>

app/views/home/_get_touch.html.erb
<div class="container">
  <div class="heading_container">
    <h2>
      Comunicate con nosotros
    </h2>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form_container contact-form">
        <form action="">
          <div class="form-row">
            <div class="col-lg-6">
              <div>
                <input type="text" placeholder="Tu nombre" />
              </div>
            </div>
            <div class="col-lg-6">
              <div>
                <input type="text" placeholder="Tu numero" />
              </div>
            </div>
          </div>
          <div>
            <input type="email" placeholder="Tu Correo electronico" />
          </div>
          <div>
            <input type="text" class="message-box" placeholder="En que podemos ayudarte?" />
          </div>
          <div class="btn_box">
            <button>
              SEND
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div id="map"></div>
    </div>
  </div>
</div>


<script>
  function initMap() {
    // Coordenadas de la ubicación que deseas mostrar en el mapa
    var myLatLng = {lat: 40.7128, lng: -74.0060}; // Por ejemplo, Nueva York

    // Crear un mapa en el elemento con id "map"
    var map = new google.maps.Map(document.getElementById('map'), {
      center: myLatLng,
      zoom: 15 // Puedes ajustar el nivel de zoom según tus necesidades
    });

    // Crear un marcador en la ubicación especificada
    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: 'Ubicación de tu empresa' // Puedes cambiar el texto del título si lo deseas
    });
  }
</script>

app/views/home/index.html.erb
<% if !current_user.present? %>
  <div class="hero_area">
    <div class="hero_bg_box">
      <%= image_tag("Banner3.png", alt: "Texto alternativo") %>
    </div>
  </div>

  <section class="about_section layout_margin-bottom" data-aos="fade-up">
    <%= render "about_us" %>
  </section>

  <section class="doctor_section layout_padding" data-aos="fade-up">
    <%= render "employes" %>
  </section>

  <section class="contact_section layout_padding" data-aos="fade-up">
    <%= render "get_touch" %>
  </section>

  <section class="client_section layout_padding-bottom" data-aos="fade-up">
    <%= render "testimonio" %>
  </section>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdsumWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


    <%= stylesheet_link_tag 'https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDc3LRykbLB-y8MuomRUIY0qH5S6xgBLX4' %>

    <%= javascript_include_tag 'main', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'bootstrap.css' %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- Font Awesome -->
    <%= stylesheet_link_tag 'font-awesome.min.css' %>

    <!-- Custom styles -->
    <%= stylesheet_link_tag 'style.css' %>

    <!-- Responsive styles -->
    <%= stylesheet_link_tag 'responsive.css' %>

    <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- owl slider -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAzXjisqz4swVKvjVUcwZv6xIzT-E7eq_c&callback=initMap" async defer></script>

    <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
    





  </head>

  <body>
    <% if !current_user.present? %>
        <header class="header_section bg-color-header">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container">
                    <a class="navbar-brand" href="index.html">
                        <span>
                            ADSUM
                        </span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <%= link_to "Inicio", root_path, class: "nav-link #{'active' if current_page?(root_path)}" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Quienes Somos", abouts_path, class: "nav-link #{'active' if current_page?(abouts_path)}" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Equipo de Trabajo", work_teams_path, class: "nav-link #{'active' if current_page?(work_teams_path)}" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Empleos", employees_path, class: "nav-link #{'active' if current_page?(employees_path)}" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Contactanos", contact_us_path, class: "nav-link #{'active' if current_page?(contact_us_path)}" %>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </header>
    <% else %>
        <header class="header_section bg-color-header">
          <div class="container">
              <nav class="navbar navbar-expand-lg custom_nav-container">
                  <a class="navbar-brand" href="index.html">
                      <span>
                          ADSUM Admin
                      </span>
                  </a>

                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                  </button>

                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                      <li class="nav-item">
                        <%= link_to "Inicio", root_path, class: "nav-link #{'active' if current_page?(root_path)}" %>
                      </li>
                      <li class="nav-item">
                        <%= link_to "Empleos", abouts_path, class: "nav-link #{'active' if current_page?(abouts_path)}" %>
                      </li>
                      <% if user_signed_in? %>
                        <li class="nav-item">
                          <%= form_tag(destroy_user_session_path, method: :delete) do %>
                            <%= submit_tag "Cerrar sesión", class: "nav-link btn btn-danger" %>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                  </div>
              </nav>
          </div>
      </header>
    <% end %>


    <%= yield %>
  </body>
    <% if !current_user.present? %>
      <footer class="footer_section">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-lg-4 footer_col">
              <div class="footer_contact">
                <h4>Reach at..</h4>
                <div class="contact_link_box">
                  <a href="#">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <span>Location</span>
                  </a>
                  <a href="tel:+011234567890">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <span>Call +01 1234567890</span>
                  </a>
                  <a href="mailto:demo@gmail.com">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                    <span>demo@gmail.com</span>
                  </a>
                </div>
                <div class="footer_social">
                  <a href="#" target="_blank" rel="noopener noreferrer">
                    <i class="fa fa-facebook" aria-hidden="true"></i>
                  </a>
                  <a href="#" target="_blank" rel="noopener noreferrer">
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                  </a>
                  <a href="#" target="_blank" rel="noopener noreferrer">
                    <i class="fa fa-linkedin" aria-hidden="true"></i>
                  </a>
                  <a href="#" target="_blank" rel="noopener noreferrer">
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                  </a>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-lg-4 mx-auto footer_col">
              <div class="footer_link_box">
                <h4>Links</h4>
                <div class="footer_links">
                  <a class="active" href="/">Home</a>
                  <a href="/about">About</a>
                  <a href="/departments">Departments</a>
                  <a href="/doctors">Doctors</a>
                  <a href="/contact">Contact Us</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
  <% end %>
</html>

<script>
    // Inicializar la librería AOS
  AOS.init({
    duration: 800, // Duración de la animación en milisegundos
    once: true // La animación solo se activará una vez
  });
</script>

app/views/work_teams/index.html.erb
<h1>WorkTeams#index</h1>
<p>Find me in app/views/work_teams/index.html.erb</p>